/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.noitom.pnstream;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
//        UpclientApp classUnderTest = new UpclientApp();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
